name: Check YouTube and Update Videos

on:
  schedule:
    # Запускать каждые 6 часов
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run the script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: python run.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"
        git add videos.json
        git diff --staged --quiet || git commit -m "Update videos.json"
        git push
