name: Check YouTube and Update Videos

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install System Dependencies (FFmpeg & Tesseract)
      run: sudo apt-get update && sudo apt-get install -y ffmpeg tesseract-ocr

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run the script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Добавили секрет для Gemini
      run: python run.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"
        if [ -f "videos.json" ]; then
          git add videos.json
          git diff --staged --quiet || git commit -m "Update videos.json"
          git push
        else
          echo "videos.json not found, nothing to commit."
        fi
