name: Check YouTube and Update Videos

on:
  schedule:
    # Запускать в ПН, ВТ, ЧТ в 12:00 и 12:30 UTC (15:00, 15:30 МСК)
    - cron: '0,30 12 * * 1,2,4'
    # Запускать в СР, СБ в 08:00 и 09:00 UTC (11:00, 12:00 МСК)
    - cron: '0 8,9 * * 3,6'
  workflow_dispatch:
    # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Run the script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: python run.py
    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"
        if [ -f "videos.json" ]; then
          git add videos.json
          git diff --staged --quiet || git commit -m "Update videos.json"
          git push
        else
          echo "videos.json not found, nothing to commit."
        fi
